### ISSUE TITLE
Generate new method by selector?

### ISSUE THREAD

**Issue by Arthraim** [MellongLau/AMMethod2Implement#14]
[feature request]

When I'm writing something like    
` [someButton addTarget:self action:@selector(buttonAction:) forControlEvents:UIControlEventTouchUpInside];`

I want to generate a method in current class context by hitting a hotkey when I have typed in the selector.

**Comment by MellongLau** [comment]
Added this feature in v2.3

**Comment by Arthraim** [comment]
Awesome work, thanks!
