### ISSUE TITLE
Create method based on invocation?

### ISSUE THREAD

**Issue by entonio** [MellongLau/AMMethod2Implement#17]
THANK YOU for this plugin. It speeds up development considerably, at least for me.
I was wondering abut the feasibility of creating methods from invocations, e.g.,

````
[self someName:YES withThingy:@"thing"]; // error: No visible @interface for ... declares the selector...
// in this case, the plugin would offer to create the stub in this .m file we're in
````

````
[otherObject someName:YES withThingy:@"thing"]; // error: No visible @interface for ... declares the selector...
// in this case, the plugin would offer to create the stub in the main .m file of otherObject and declare it in the main .h
````

If the type of the params is hard to infer, then forget the .h part (AMM2I can deal with that later on) and make everything type `id` and xcode-highlighted. It will still be s great time saver.
````
- (<#id#>) someName:(<#id#>)someName withThingy:(<#id#>)withThingy 
````

It's something I'd try to implement, myself, but I have no experience with this, At least I'd love to know the difficulty level of doing it. Thanks!

**Comment by MellongLau** [comment]
Added parameterless method invocation in
https://github.com/MellongLau/AMMethod2Implement/commit/29be274b2c85777edaf6b3cc71f335ada8f5498e
