### ISSUE TITLE
XCode 6.3 found a bug

### ISSUE THREAD

**Issue by BillZong** [MellongLau/AMMethod2Implement#19]
The plugin is cool, but I found a bug when it's running in Version 6.3 (6D570).
since I was using it in objective-c, when I'm choosing the menu command method, the result string is print out with "\n\t",  sort of things.
Hope the autor could check it out.

**Comment by MellongLau** [comment]
Thanks, this issue is duplicate https://github.com/MellongLau/AMMethod2Implement/issues/18，fixed in latest build, please reinstall it.
