### ISSUE TITLE
It's not support declare a method in extension

### ISSUE THREAD

**Issue by geek5nan** [MellongLau/AMMethod2Implement#20]
I have try to declared a method in `@implements ClassName` to `@interface ClassName` is OK,but declared a method in `@implements ClassName` to `@interface ClassName()` is not work

**Comment by MellongLau** [comment]
I think it is no need to declared a method in @implements ClassName to @interface ClassName(), 
but @implements ClassName (Extension) to @interface ClassName(Extension) should work.
