### ISSUE TITLE
can not use

### ISSUE THREAD

**Issue by hejunbinlan** [MellongLau/AMMethod2Implement#22]
I can see the plugin :"~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/AMMethod2Implement.xcplugin"
but:
I can not see "menu `Edit` > `AMMethod2Implement` > `Implement Method`."
and Use key `Ctrl+A` invalid

xcode 6.3.2
why not?

**Comment by pengrun8** [comment]
Me too.

**Comment by MellongLau** [comment]
Fixed in 1c212a4, please install the latest version and try again.
