### ISSUE TITLE
为啥在.m实现method或者@selector，方法在顶部实现？？

### ISSUE THREAD

**Issue by ad0ma** [MellongLau/AMMethod2Implement#31]
![image](https://cloud.githubusercontent.com/assets/14819041/14482221/1d8bf5e2-016d-11e6-87d9-143769730292.png)

**Comment by MellongLau** [comment]
Hi @ad0ma ，能否提供一下重现的步骤

**Comment by MellongLau** [comment]
No more response, so close this issue.
