### ISSUE TITLE
Crash on Xcode 5.1.1/Mavericks

### ISSUE THREAD

**Issue by davidganster** [MellongLau/AMMethod2Implement#5]
Getting the following crash report in Xcode when trying to generate implementation code for any method:

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
Sending doImplementMethodAction to <AMMethod2Implement: 0x7fcc74570a70> from <NSMenuItem: 0x7fcc7439b0f0 Implement Method (v1.2)>
ProductBuildVersion: 5B1008
UNCAUGHT EXCEPTION (NSRangeException): *** -[__NSCFString rangeOfString:options:range:locale:]: Range {9223372036854775807, 9223372036854777977} out of bounds; string length 2168

Tried with methods with and without parameters.
OS X Mavericks 10.9.2, 2009 iMac

**Comment by MellongLau** [comment]
Please use the latest xcode.
