### ISSUE TITLE
Allow changing the keyboard shortcut

### ISSUE THREAD

**Issue by thurn** [MellongLau/AMMethod2Implement#9]
Ctrl-A is a very important shortcut for emacs users. Is there any way to customize what shortcut this plugin uses?

**Comment by MellongLau** [comment]
Hi, you can change this hotkey via the Keyboard Shortcuts Panel in the System Preferences.

Open System Preferences
Go to Keyboard
Switch to the Shortcuts tab
Select App Shortcuts and click the + Button.
Select Xcode.app
Enter Action Bar as Menu Title (like "Implement Method (v2.3)")
Enter the Shortcut you want
